# Generated by Django 5.2.4 on 2025-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.TextField(verbose_name='信息内容')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='反馈时间')),
            ],
        ),
    ]
